class AddDefaultSeasonToSports < ActiveRecord::Migration[7.0]
  def up
    add_reference :sports, :season, foreign_key: true
    Sport.reset_column_information
    spring = Season.find_by!(name: "Spring")
    winter = Season.find_by!(name: "Winter")
    year_round = Season.find_by!(name: "Year-round")
    fall = Season.find_by!(name: "Fall")

    Sport.find_by(name: "Volleyball").update!(season_id: fall.id)
    Sport.find_by(name: "Volleyball").teams.update_all(season_id: fall.id)
    Sport.find_by(name: "Cross Country").update!(season_id: fall.id)
    Sport.find_by(name: "Cross Country").teams.update_all(season_id: fall.id)
    Sport.find_by(name: "Football").update!(season_id: fall.id)
    Sport.find_by(name: "Football").teams.update_all(season_id: fall.id)
    Sport.find_by(name: "Soccer").update!(season_id: fall.id)
    Sport.find_by(name: "Soccer").teams.update_all(season_id: fall.id)
    Sport.find_by(name: "Sideline Cheer").update!(season_id: fall.id)
    Sport.find_by(name: "Sideline Cheer").teams.update_all(season_id: fall.id)
    Sport.find_by(name: "Band").update!(season_id: fall.id)
    Sport.find_by(name: "Band").teams.update_all(season_id: fall.id)
    Sport.find_by(name: "Field Hockey").update!(season_id: fall.id)
    Sport.find_by(name: "Field Hockey").teams.update_all(season_id: fall.id)
    Sport.find_by(name: "Football Cheer").update!(season_id: fall.id)
    Sport.find_by(name: "Football Cheer").teams.update_all(season_id: fall.id)
    Sport.find_by(name: "Soccer MS").update!(season_id: fall.id)
    Sport.find_by(name: "Soccer MS").teams.update_all(season_id: fall.id)
    Sport.find_by(name: "Youth Football").update!(season_id: fall.id)
    Sport.find_by(name: "Youth Football").teams.update_all(season_id: fall.id)
    Sport.find_by(name: "Volleyball ").update!(season_id: fall.id)
    Sport.find_by(name: "Volleyball ").teams.update_all(season_id: fall.id)
    Sport.find_by(name: "Tennis").update!(season_id: fall.id)
    Sport.find_by(name: "Tennis").teams.update_all(season_id: fall.id)
    Sport.find_by(name: "Golf").update!(season_id: fall.id)
    Sport.find_by(name: "Golf").teams.update_all(season_id: fall.id)

    Sport.find_by(name: "Bowling").update!(season_id: winter.id)
    Sport.find_by(name: "Bowling").teams.update_all(season_id: winter.id)
    Sport.find_by(name: "Swimming").update!(season_id: winter.id)
    Sport.find_by(name: "Swimming").teams.update_all(season_id: winter.id)
    Sport.find_by(name: "Wrestling").update!(season_id: winter.id)
    Sport.find_by(name: "Wrestling").teams.update_all(season_id: winter.id)
    Sport.find_by(name: "Competitive Cheer").update!(season_id: winter.id)
    Sport.find_by(name: "Competitive Cheer").teams.update_all(season_id: winter.id)
    Sport.find_by(name: "Gymnastics").update!(season_id: winter.id)
    Sport.find_by(name: "Gymnastics").teams.update_all(season_id: winter.id)
    Sport.find_by(name: "Basketball").update!(season_id: winter.id)
    Sport.find_by(name: "Basketball").teams.update_all(season_id: winter.id)
    Sport.find_by(name: "Dance").update!(season_id: winter.id)
    Sport.find_by(name: "Dance").teams.update_all(season_id: winter.id)
    Sport.find_by(name: "Hockey").update!(season_id: winter.id)
    Sport.find_by(name: "Hockey").teams.update_all(season_id: winter.id)
    Sport.find_by(name: "Indoor Track").update!(season_id: winter.id)
    Sport.find_by(name: "Indoor Track").teams.update_all(season_id: winter.id)
    Sport.find_by(name: "Diving").update!(season_id: winter.id)
    Sport.find_by(name: "Diving").teams.update_all(season_id: winter.id)
    Sport.find_by(name: "Basketball Cheer").update!(season_id: winter.id)
    Sport.find_by(name: "Basketball Cheer").teams.update_all(season_id: winter.id)
    Sport.find_by(name: "Winter Track and Field").update!(season_id: winter.id)
    Sport.find_by(name: "Winter Track and Field").teams.update_all(season_id: winter.id)
    Sport.find_by(name: "Winter Guard").update!(season_id: winter.id)
    Sport.find_by(name: "Winter Guard").teams.update_all(season_id: winter.id)
    Sport.find_by(name: "Wrestling (Girls)").update!(season_id: winter.id)
    Sport.find_by(name: "Wrestling (Girls)").teams.update_all(season_id: winter.id)
    Sport.find_by(name: "Knowledge Bowl").update!(season_id: winter.id)
    Sport.find_by(name: "Knowledge Bowl").teams.update_all(season_id: winter.id)

    Sport.find_by(name: "Track").update!(season_id: spring.id)
    Sport.find_by(name: "Track").teams.update_all(season_id: spring.id)
    Sport.find_by(name: "Baseball").update!(season_id: spring.id)
    Sport.find_by(name: "Baseball").teams.update_all(season_id: spring.id)
    Sport.find_by(name: "Softball").update!(season_id: spring.id)
    Sport.find_by(name: "Softball").teams.update_all(season_id: spring.id)
    Sport.find_by(name: "Lacrosse").update!(season_id: spring.id)
    Sport.find_by(name: "Lacrosse").teams.update_all(season_id: spring.id)
    Sport.find_by(name: "Track and Field").update!(season_id: spring.id)
    Sport.find_by(name: "Track and Field").teams.update_all(season_id: spring.id)

    Sport.find_by(name: "Quiz").update!(season_id: year_round.id)
    Sport.find_by(name: "Quiz").teams.update_all(season_id: year_round.id)
    Sport.find_by(name: "Athletic Training").update!(season_id: year_round.id)
    Sport.find_by(name: "Athletic Training").teams.update_all(season_id: year_round.id)
    Sport.find_by(name: "Quick Recall").update!(season_id: year_round.id)
    Sport.find_by(name: "Quick Recall").teams.update_all(season_id: year_round.id)
    Sport.find_by(name: "Cheerleading").update!(season_id: year_round.id)
    Sport.find_by(name: "Cheerleading").teams.update_all(season_id: year_round.id)
    Sport.find_by(name: "School").update!(season_id: year_round.id)
    Sport.find_by(name: "School").teams.update_all(season_id: year_round.id)
    Sport.find_by(name: "FFA").update!(season_id: year_round.id)
    Sport.find_by(name: "FFA").teams.update_all(season_id: year_round.id)
    Sport.find_by(name: "Art Club").update!(season_id: year_round.id)
    Sport.find_by(name: "Art Club").teams.update_all(season_id: year_round.id)
  end

  def down
    remove_reference :sports, :season, foreign_key: true
  end
end
